version: "3.2"
services:
  graphapi:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - mongodb
    command:
      - "--mongo-uri=mongodb://mongodb:27017/movies"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
